### ISSUE TITLE
Add flag to dump the context matrix

### ISSUE THREAD

**Issue by sebpuetz** [finalfusion/finalfrontier#25]
I see two ways:

1. Extend `finalfusion` to handle files with both input and output matrices
2. Dump the output matrix + vocab in a seperate `finalfusion` model.

Re 1.: More work and might make APIs (more) complex.
Re 2.: Hackier solution, output types need to implement `to_string()`. Lookup consequently also done through stringly keys.

**Comment by danieldk** [comment]
It would be nice to have it, but post-0.5.

**Comment by sebpuetz** [comment]
I had a look into this today, this is messy. 

The only case where serialization of a context-model is straight forward, is for skipgram. Although structgram and dirgram both have stringly keys, we still need some additional typing in order to distinguish between different offsets. This could certainly be done by appending numbers to the vocab items, but we'd need to handle this for all models differently and wouldn't be able to do so in a common implementation.

Also, while writing this I ended up with this monster of a fn signature for a generic implementation of the writing trait:

```Rust
impl<W, T, IV, OV, M> WriteModelBinaryWithContexts<W> for TrainModel<T>
where
    W: Seek + Write,
    T: Trainer<InputVocab = IV, OutputVocab = OV, Metadata = M>,
    M: Serialize,
    IV: Vocab<VocabType = String>,
    for<'a> &'a IV::IdxType: IntoIterator<Item = u64>,
    OV: Vocab<VocabType = String>,
    for<'a> &'a OV::IdxType: IntoIterator<Item = u64>,
    for<'b> VocabWrap: From<&'b IV> + From<&'b OV>,
```

**Comment by danieldk** [comment]
Meh, too large a type signature indeed.

**Comment by sebpuetz** [comment]
I'm not working on this and I don't think there's any interest for it, closing this for now.
