### ISSUE TITLE
Update man pages

### ISSUE THREAD

**Issue by danieldk** [finalfusion/finalfrontier#26]
- [x] `ff-train`: verify that the options are still in sync
- [x] `ff-deps`: write the manpage

**Comment by sebpuetz** [comment]
I assume, we should include a reference to the dependency embeddings paper in the ff-deps manpage?

**Comment by danieldk** [comment]
No, I would put that in the README under models. There are sometimes references in man pages, but IMO man pages should solely focus on providing the information necessary to run a program on the command-line.

**Comment by danieldk** [comment]
BTW., you could put in a short references as I did in the ff-train manpage (under the `model` option).

**Comment by sebpuetz** [comment]
Solved by #37
